import {fresh,stats,guide,round,split,validate,monthKey,nextMonth} from './core.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>Number(n).toLocaleString('ar-EG',{maximumFractionDigits:2}),key='month-step-v1';
let state;try{state=validate(JSON.parse(localStorage.getItem(key))||fresh());}catch{state=fresh();setTimeout(()=>toast('تعذّر قراءة البيانات. لم نستبدل النسخة القديمة؛ نزّلها من الإعدادات قبل الحفظ.'),200);}
let current=state.months.at(-1).id,tab='home',editing=null;
const month=()=>state.months.find(m=>m.id===current),date=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4500);}
function save(){try{validate(state);for(const m of state.months){const check=stats(state,m);if(check.cash<0||Object.values(check.debt).some(d=>d<0))throw Error('التعديل يجعل الرصيد أو الدين سالبًا؛ راجع الحركات المرتبطة');}localStorage.setItem(key,JSON.stringify(state));render();toast('تم الحفظ على جهازك');return true;}catch(e){try{const old=localStorage.getItem(key);if(old){state=validate(JSON.parse(old));if(!state.months.some(m=>m.id===current))current=state.months.at(-1).id;render();}}catch{}toast('تعذّر الحفظ: '+e.message);return false;}}
const button=(text,act,args='')=>`<button data-action="${act}" ${args}>${text}</button>`;
function render(){const m=month(),s=stats(state,m),g=guide(state,m),cfg=state.settings;$('#month').innerHTML=state.months.map(x=>`<option value="${x.id}" ${x.id===current?'selected':''}>${new Date(x.id+'-02').toLocaleDateString('ar-EG',{month:'long',year:'numeric'})}</option>`).join('');
const income=m.transactions.filter(t=>t.type==='income').reduce((a,t)=>a+t.amount,0),expenses=m.transactions.filter(t=>['expense','installment'].includes(t.type)).reduce((a,t)=>a+t.amount,0),planned=m.budgets.reduce((a,b)=>a+b.amount,0);
$('#home').innerHTML=`<div class="grid">${[['الرصيد الفعلي',s.cash],['محجوز للأكل',s.reserved],['المتاح للصرف',s.available],['التزامات متبقية',s.remaining]].map(([label,n])=>`<div class="tile"><small>${label}</small><strong class="${n<0?'negative':''}">${money(n)}</strong><span class="unit">جنيه مصري</span></div>`).join('')}</div><div class="layout"><div><article class="step"><span class="pill">◈ الخطوة التالية</span><h2>${esc(g.title)}</h2><p>${esc(g.detail)}</p>${g.amount?`<strong>${money(g.principal??g.amount)} جنيه</strong>`:''}${g.held?`<p>محجوز إضافي للالتزامات أثناء الانتظار: ${money(g.held)} جنيه</p>`:''}<div class="actions">${['blocked','wait'].includes(g.action)?button('تسجيل دخل','income'):button({review:'مراجعة الإعدادات',income:'استلمت الدخل',reserve:'حجز الأكل',expense:'دفعت',installment:'سددت القسط',repay:'سددت',withdraw:'استلمت السحب',budget:'فتح الميزانية'}[g.action],'next','class="primary"')}${button('مصروف جديد','expense')}${button('دخل إضافي','income','data-source="part"')}</div></article><div class="notice">الدخل المتوقع: ${money(875*cfg.rate)} جنيه • المصروفات المخططة: ${money(planned)} جنيه قبل الرسوم. ${875*cfg.rate<planned?'الدخل المتوقع أقل من الالتزامات؛ راجع العجز قبل الصرف.':''}<br>رسوم السداد غير المسجلة تجعل التقديرات غير مكتملة.</div></div><article class="box"><h3>حركة الشهر</h3><p class="help">الأساسي: يوم 1 • الإضافي: حتى يوم 5 (${m.transactions.some(t=>t.type==='income'&&t.source==='part')?'تم تسجيله':'لم يُستلم بعد'})</p><div class="row"><span>الدخل المقبوض</span><strong>${money(income)}</strong></div><div class="row"><span>مصروفات وقسط مسجلة</span><strong>${money(expenses)}</strong></div><div class="row"><span>المخطط / الفعلي مع تخفيض الدين</span><strong>${money(planned)} / ${money(expenses+Object.values(s.cycles).reduce((a,c)=>a+Math.max(0,c.paid-c.drawn),0))}</strong></div><div class="row"><span>رسوم العمليات</span><strong>${money(s.fees)}</strong></div><div class="row"><span>صافي تقليل دين البطاقات</span><strong>${money(Object.values(s.cycles).reduce((a,c)=>a+c.paid-c.drawn,0))}</strong></div><p class="help">السداد والسحب حركات نقدية منفصلة. أصل السحب لا يُحسب دخلًا، وأصل السداد لا يتكرر كمصروف.</p></article></div>`;
$('#budget').innerHTML=`<div class="sectionHead"><h2>كل جنيه له مكان</h2>${button('تسجيل مصروف','expense')}</div><div class="list">${m.budgets.map(b=>`<article class="budgetItem"><div class="row"><div><b>${esc(b.name)}</b><small>موعد مستهدف: يوم ${b.due} • مدفوع ${money(s.paid[b.id]||0)}</small></div><strong>${money(Math.max(0,b.amount-(s.paid[b.id]||0)))}<small>متبقي من ${money(b.amount)}</small></strong></div><div class="progress"><span style="width:${Math.min(100,(s.paid[b.id]||0)/Math.max(1,b.amount)*100)}%"></span></div><div class="actions">${b.id==='credit'?button('سداد قسط','installment'):button('دفعت','expense',`data-budget="${b.id}"`)}${button('تعديل الخطة','budgetEdit',`data-budget="${b.id}"`)}</div></article>`).join('')}</div>`;
$('#cards').innerHTML=`<h2>سداد، انتظار، ثم استلام</h2><p class="help">موعد السداد وإتاحة السحب تقديرات قابلة للتعديل. سجّل الرسوم والمديونية طبقًا لكشف البنك؛ التطبيق لا يؤكد إعفاء العمليات من الفوائد.</p><div class="list">${cfg.cards.map(c=>{const cy=s.cycles[c.id];return `<article class="box"><h3>${esc(c.name)}</h3><small>آخر سداد: يوم ${c.due}</small><h2>${money(s.debt[c.id])} جنيه</h2><p class="help">سداد الشهر ${money(cy?.paid||0)} • سحب الشهر ${money(cy?.drawn||0)}</p><div class="actions">${button('سددت','repay',`data-card="${c.id}"`)}${button('استلمت السحب','withdraw',`data-card="${c.id}"`)}</div></article>`;}).join('')}<article class="box"><h3>NBK A</h3><h2>${cfg.installmentActive?money(cfg.installment)+' جنيه شهريًا':'القسط منتهٍ'}</h2><p class="help">عدد الأقساط المتبقية غير معروف. يظل القسط فعالًا حتى تؤكد انتهاءه في الإعدادات.</p>${button('سددت القسط','installment')}</article></div><div class="box" style="margin-top:18px"><h3>تقدير رسوم إعادة السحب</h3>${cfg.cards.map(c=>{const amount=Math.max(0,s.debt[c.id]-(c.id==='nbk'?cfg.creditBudget-(cfg.installmentActive?cfg.installment:0):0));return `<p class="help">${esc(c.name)}: ${split(amount).map(money).join(' + ')||'0'} • رسوم ${money(amount*cfg.fee/100)} • صافي ${money(amount*(1-cfg.fee/100))}</p>`;}).join('')}</div>`;
$('#history').innerHTML=`<div class="sectionHead"><h2>سجل الحركات</h2>${button('دخل جديد','income')}</div><div class="box">${m.transactions.length?`<div class="tableWrap"><table><thead><tr><th>التاريخ</th><th>الحركة</th><th>المبلغ</th><th>الإجراءات</th></tr></thead><tbody>${[...m.transactions].reverse().map(t=>`<tr><td>${esc(t.date)}</td><td>${esc(({income:'دخل',expense:'مصروف',installment:'قسط NBK A',repay:'سداد بطاقة',withdraw:'سحب بطاقة'})[t.type])}<small style="display:block">${esc(t.note||m.budgets.find(b=>b.id===t.budget)?.name||cfg.cards.find(c=>c.id===t.card)?.name||'')}</small></td><td class="money">${money(t.amount)}${t.type==='withdraw'?`<small style="display:block">صافي ${money(t.net)}</small>`:''}${t.type==='repay'?`<small style="display:block">رسوم ${money(t.fee)}</small>`:''}</td><td>${button('تعديل','edit',`data-id="${esc(t.id)}"`)} ${button('حذف','delete',`data-id="${esc(t.id)}"`)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty">لسه مفيش حركات. ابدأ بتسجيل الدخل المقبوض.</p>'}</div>`;
$('#settings').innerHTML=`<div class="settingsGrid"><form id="config" class="box"><h2>أرقامك ومواعيدك</h2><div class="inline"><label>سعر الدولار بالجنيه<input name="rate" type="number" min="0.01" step="0.01" value="${cfg.rate}" required></label><label>انتظار السحب بالأيام<input name="wait" type="number" min="0" max="30" value="${cfg.wait}" required></label><label>رسوم فوري %<input name="fee" type="number" min="0" max="100" step="0.01" value="${cfg.fee}" required></label><label>ميزانية الكريديت<input name="creditBudget" type="number" min="0" step="0.01" value="${cfg.creditBudget}" required></label><label>قسط NBK A<input name="installment" type="number" min="0" step="0.01" value="${cfg.installment}" required></label><label>رصيد بداية الشهر<input name="opening" type="number" min="0" step="0.01" value="${m.opening}" required></label></div><label><input name="installmentActive" type="checkbox" ${cfg.installmentActive?'checked':''}> قسط NBK A مستمر</label>${cfg.cards.map(c=>`<div class="inline"><label>دين ${esc(c.name)} قبل أول شهر<input name="${c.id}Debt" type="number" min="0" step="0.01" value="${c.debt}" required></label><label>آخر سداد يوم<input name="${c.id}Due" type="number" min="1" max="31" value="${c.due}" required></label></div>`).join('')}<p class="help">تعديل الدين الافتتاحي يؤثر على حساب الدين عبر كل الشهور. سعر التحويل لا يغير الدخل المسجل سابقًا.</p><button class="primary">حفظ وتأكيد مراجعة الشهر</button></form><article class="box"><h2>نسخة من كل بياناتك</h2><p class="help">يشمل الملف الإعدادات والشهور وجميع الحركات. انقله إلى أي جهاز وافتحه في نفس التطبيق.</p>${button('تنزيل نسخة كاملة','export','class="primary"')}<label style="margin-top:25px">استيراد نسخة JSON<input id="import" type="file" accept=".json,application/json"></label>${button('تنزيل البيانات الخام الحالية','rawExport')}<div class="notice">الاستيراد يستبدل بيانات هذا الجهاز بعد تأكيدك. نزّل نسخة قبل الاستيراد. حذف بيانات المتصفح يحذف السجل المحلي.</div><h3>تثبيت التطبيق</h3><p class="help">على أندرويد: قائمة المتصفح ← تثبيت التطبيق. على آيفون: افتحه في Safari ← مشاركة ← إضافة إلى الشاشة الرئيسية. افتحه مرة متصلًا بالإنترنت لتجهيز العمل أوفلاين.</p></article></div>`;
document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==tab);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
$('#config').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const candidate=structuredClone(state),cs=candidate.settings;for(const k of ['rate','wait','fee','creditBudget','installment'])cs[k]=Number(f.get(k));cs.installmentActive=f.has('installmentActive');if(cs.installmentActive&&cs.installment>cs.creditBudget)return toast('القسط لا يمكن أن يتجاوز ميزانية الكريديت');for(const c of cs.cards){c.debt=Number(f.get(c.id+'Debt'));c.due=Number(f.get(c.id+'Due'));}const cm=candidate.months.find(x=>x.id===current);cm.opening=Number(f.get('opening'));cm.reviewed=true;cm.budgets.find(b=>b.id==='credit').amount=cs.creditBudget+(cm.installmentCarry||0);try{validate(candidate);state=candidate;save();}catch(err){toast(err.message);}};
$('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5e6)throw Error('حجم الملف أكبر من الحد المسموح');const data=validate(JSON.parse(await file.text()));if(confirm(`استبدال بياناتك بنسخة تحتوي على ${data.months.length} شهر؟ نزّل نسخة من بياناتك الحالية أولًا.`)){state=data;current=state.months.at(-1).id;save();}}catch(err){toast('لم يتم الاستيراد: '+err.message);e.target.value='';}};
}
function field(label,name,value,type='number',more=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" step="0.01"':''} ${more} required></label>`;}
function open(type,args={},transaction=null){editing={type,args,id:transaction?.id};const t=transaction||{},m=month(),s=stats(state,m);$('#dialogTitle').textContent=({income:'تسجيل دخل مقبوض',expense:'تسجيل مصروف',installment:'قسط NBK A',repay:'سداد بطاقة',withdraw:'استلام سحب',budgetEdit:'تعديل بند الميزانية'})[type];let html='';
if(type==='budgetEdit'){const b=m.budgets.find(b=>b.id===args.budget);html=field('المبلغ المخطط','amount',b.amount)+field('اليوم المستهدف','due',b.due,'number','max="31"');}
else{if(type==='income')html=`<label>مصدر الدخل<select name="source">${[['full','العمل الأساسي • 675 دولار'],['part','العمل الإضافي • 200 دولار'],['other','دخل آخر']].map(([id,label])=>`<option value="${id}" ${(t.source||args.source)===id?'selected':''}>${label}</option>`).join('')}</select></label><p class="help">السعر الحالي ${money(state.settings.rate)} جنيه. سجّل الصافي الفعلي بعد أي رسوم.</p>`;
if(type==='expense')html=`<label>بند المصروف<select name="budget">${m.budgets.filter(b=>b.id!=='credit').map(b=>`<option value="${b.id}" ${(t.budget||args.budget)===b.id?'selected':''}>${esc(b.name)}</option>`).join('')}</select></label>`;
if(['repay','withdraw'].includes(type))html=`<label>البطاقة<select name="card">${state.settings.cards.map(c=>`<option value="${c.id}" ${(t.card||args.card)===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>`;
let value=t.amount??args.principal??args.amount??(type==='installment'?state.settings.installment:type==='income'?(args.source==='part'?200:675)*state.settings.rate:0);
html+=field(type==='withdraw'?'المبلغ المخصوم من البطاقة (حتى 10000)':'المبلغ بالجنيه','amount',value,'number',type==='withdraw'?'max="10000"':'');
if(type==='repay')html+=field('رسوم السداد الفعلية (اكتب 0 إذا لا توجد)','fee',t.fee??'');
if(type==='withdraw')html+=field('صافي الكاش المستلم','net',t.net??round(value*(1-state.settings.fee/100)));
html+=field('تاريخ الحركة','date',t.date||date(),'date')+`<label>ملاحظة<input name="note" value="${esc(t.note||'')}" maxlength="250"></label><p class="help">المتاح قبل الحركة: ${money(s.available)} جنيه. التسجيل يؤثر على الرصيد فورًا.</p>`;}
$('#fields').innerHTML=html;$('#error').textContent='';$('#modal').showModal();if(type==='withdraw')$('#fields [name=amount]').oninput=e=>$('#fields [name=net]').value=round(Number(e.target.value)*(1-state.settings.fee/100));}
$('#entry').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),{type,args,id}=editing,m=month();try{if(type==='budgetEdit'){const amount=Number(f.get('amount')),due=Number(f.get('due'));if(due<1||due>31||!Number.isInteger(due))throw Error('الموعد من 1 إلى 31');Object.assign(m.budgets.find(b=>b.id===args.budget),{amount,due,baseAmount:amount});}else{const t={id:id||crypto.randomUUID(),type,amount:Number(f.get('amount')),date:f.get('date'),note:f.get('note')||''};if(t.amount<=0)throw Error('اكتب مبلغًا أكبر من صفر');if(!t.date.startsWith(m.id))throw Error('تاريخ الحركة لازم يكون داخل الشهر المختار');if(type==='income')t.source=f.get('source');if(type==='expense')t.budget=f.get('budget');if(type==='installment')t.budget='credit';if(['repay','withdraw'].includes(type))t.card=f.get('card');if(type==='repay')t.fee=Number(f.get('fee'));if(type==='withdraw'){t.net=Number(f.get('net'));if(t.amount>10000||t.net>t.amount)throw Error('راجع حد العملية وصافي السحب');}
const candidate=structuredClone(state),cm=candidate.months.find(x=>x.id===current);if(id)cm.transactions=cm.transactions.map(x=>x.id===id?t:x);else cm.transactions.push(t);validate(candidate);const before=stats(state,m),after=stats(candidate,cm);if(Object.values(after.debt).some(d=>d<0))throw Error('السداد يتجاوز الدين المسجل؛ راجع الرصيد');if(after.cash<0)throw Error('الرصيد الفعلي لا يكفي لتسجيل هذه العملية');if(after.available<0&&after.available<before.available&&!confirm('هذه الحركة ستستخدم جزءًا من ميزانية الأكل المحجوزة. هل تؤكد تسجيلها؟'))return;state=candidate;}
if(save())$('#modal').close();}catch(err){$('#error').textContent=err.message;}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){tab=b.dataset.tab;render();return;}const act=b.dataset.action;if(!act)return;const args={budget:b.dataset.budget,card:b.dataset.card,source:b.dataset.source};if(act==='next'){const g=guide(state,month());if(g.action==='review'){tab='settings';render();}else if(g.action==='reserve'){const s=stats(state,month());if(s.cash<g.amount)return toast('الرصيد لا يكفي لحجز ميزانية الأكل');month().foodReserved=true;save();}else if(g.action==='budget'){tab='budget';render();}else open(g.action,g);}
else if(['income','expense','repay','withdraw','installment','budgetEdit'].includes(act))open(act,args);
else if(act==='edit'){const t=month().transactions.find(t=>t.id===b.dataset.id);open(t.type,{},t);}
else if(act==='delete'&&confirm('حذف هذه الحركة وإعادة حساب الرصيد؟')){month().transactions=month().transactions.filter(t=>t.id!==b.dataset.id);save();}
else if(act==='export'||act==='rawExport'){const content=act==='export'?JSON.stringify(state,null,2):localStorage.getItem(key)||JSON.stringify(state);const url=URL.createObjectURL(new Blob([content],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`month-step-${date()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
$('#close').onclick=()=>$('#modal').close();$('#month').onchange=e=>{current=e.target.value;render();};
$('#newMonth').onclick=()=>{const last=state.months.at(-1),d=new Date(last.id+'-02');d.setMonth(d.getMonth()+1);const id=monthKey(d);if(!confirm(`فتح شهر ${id} وترحيل الرصيد والالتزامات غير المدفوعة؟ الالتزامات المرحّلة تضاف لميزانية الشهر الجديد.`))return;const s=stats(state,last);if(s.cash<0)return toast('صحح الرصيد السالب أولًا');const m=nextMonth(state);state.months.push(m);current=id;save();};
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false;});$('#install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('#install').hidden=true;}};
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>toast('لم يتم تجهيز العمل أوفلاين؛ حاول فتح التطبيق متصلًا بالإنترنت.'));
render();

const themeButton=$('#theme'),systemTheme=matchMedia('(prefers-color-scheme: dark)');
function applyTheme(theme){document.documentElement.dataset.theme=theme;const dark=theme==='dark';themeButton.textContent=dark?'الوضع الفاتح ☀':'الوضع الداكن ☾';themeButton.setAttribute('aria-pressed',String(dark));themeButton.setAttribute('aria-label',dark?'تفعيل الوضع الفاتح':'تفعيل الوضع الداكن');document.querySelector('meta[name="theme-color"]').content=dark?'#101c1a':'#123f37';}
applyTheme(document.documentElement.dataset.theme||'light');
themeButton.onclick=()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';applyTheme(theme);try{localStorage.setItem('month-step-theme',theme);}catch{toast('تم تغيير المظهر، لكن تعذّر حفظ الاختيار على الجهاز');}};
systemTheme.addEventListener('change',e=>{try{if(!localStorage.getItem('month-step-theme'))applyTheme(e.matches?'dark':'light');}catch{}});
