export const defaults = [ ['food','الأكل',6500],['charity','الصدقة',6500],['rent','الإيجار',4300],['electric','الكهرباء',500],['gas','الغاز',200],['water','المياه',100],['nursery','حضانة حور',2400],['hour','حور',1100],['wife','مصاريف مراتي',700],['wifeGroup','جمعية مراتي',500],['groups','الجمعيات',10000],['credit','ميزانية الكريديت',2000],['internet','الإنترنت',600],['personal','مصاريفي الشخصية',700],['health','علاج وطوارئ',700],['ai','مصاريف AI',1000],['car','العربية',1300] ];
export const monthKey = (date=new Date()) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;
export function fresh(){ return {version:1,settings:{rate:50,wait:2,fee:1,installment:1500,creditBudget:2000,installmentActive:true,cards:[{id:'nbk',name:'NBK محمد',debt:20000,due:20},{id:'nbe',name:'NBE محمد',debt:10194,due:20}]},months:[{id:monthKey(),opening:0,reviewed:false,foodReserved:false,budgets:defaults.map(([id,name,amount])=>({id,name,amount,due:id==='rent'||id==='charity'?1:20})),transactions:[]}]}; }
export const round = n => Math.round(n*100)/100;
export function split(amount){let result=[];for(let remaining=round(amount);remaining>0;remaining=round(remaining-Math.min(10000,remaining)))result.push(Math.min(10000,remaining));return result;}
export function stats(state,month){
 let cash=month.opening,fees=0;const paid={},debt=Object.fromEntries(state.settings.cards.map(c=>[c.id,c.debt])),cycles={};
 for(const m of state.months){for(const t of m.transactions){if(t.type==='repay')debt[t.card]-=t.amount;if(t.type==='withdraw')debt[t.card]+=t.amount;}if(m.id===month.id)break;}
 for(const t of month.transactions){if(t.type==='income')cash+=t.amount;if(t.type==='expense'||t.type==='installment'){cash-=t.amount;paid[t.budget]=(paid[t.budget]||0)+t.amount;}if(t.type==='repay'){cash-=t.amount+t.fee;fees+=t.fee;const c=cycles[t.card]??={paid:0,drawn:0,last:t.date};c.paid+=t.amount;if(t.date>c.last)c.last=t.date;}if(t.type==='withdraw'){cash+=t.net;fees+=t.amount-t.net;const c=cycles[t.card]??={paid:0,drawn:0,last:t.date};c.drawn+=t.amount;}}
 const food=month.budgets.find(b=>b.id==='food');const reserved=month.foodReserved?Math.max(0,food.amount-(paid.food||0)):0;
 const creditPaid=month.transactions.filter(t=>t.type==='installment').reduce((s,t)=>s+t.amount,0)+Object.values(cycles).reduce((s,c)=>s+Math.max(0,c.paid-c.drawn),0);
 paid.credit=creditPaid;
 return {cash:round(cash),fees:round(fees),paid,debt,cycles,reserved,available:round(cash-reserved),remaining:round(month.budgets.reduce((s,b)=>s+Math.max(0,b.amount-(paid[b.id]||0)),0))};
}
export function guide(state,m,today=new Date()){
 const s=stats(state,m),config=state.settings; const step=(title,detail,action,amount=0,extra={})=>({title,detail,action,amount,...extra});
 if(!m.reviewed)return step('راجع أرقام الشهر أولًا','أكد سعر الصرف والأرصدة والمواعيد من الإعدادات.','review');
 if(!m.transactions.some(t=>t.type==='income'&&t.source==='full'))return step('استلمت مرتبك الأساسي؟','سجّل صافي الجنيه الذي دخل فعلًا. الدخل المتوقع لا يزيد الرصيد.','income',675*config.rate,{source:'full'});
 if(!m.foodReserved)return step('احجز ميزانية الأكل','6500 جنيه للشهر، والحجز لا يسجل دفعًا.','reserve',m.budgets.find(b=>b.id==='food').amount);
 const safe=(title,amount,action,extra={})=>s.available>=amount?step(title,'المبلغ متاح بعد حماية ميزانية الأكل.',action,amount,extra):step('السيولة لا تكفي للخطوة التالية',`${title} يحتاج ${amount.toLocaleString('ar-EG')} جنيه. العجز ${round(amount-s.available).toLocaleString('ar-EG')} جنيه. انتظر دخلًا فعليًا أو راجع الالتزامات.`, 'blocked',amount,extra);
 for(const [id,target] of [['rent',m.budgets.find(b=>b.id==='rent').amount],['charity',Math.min(3000,m.budgets.find(b=>b.id==='charity').amount)]]){const left=target-(s.paid[id]||0);if(left>0)return safe(id==='rent'?'ادفع الإيجار':'ادفع أول 3000 من الصدقة',left,'expense',{budget:id});}
 const nbkOpening=s.debt.nbk+(s.cycles.nbk?.paid||0)-(s.cycles.nbk?.drawn||0);
 for(const card of config.cards){const c=s.cycles[card.id];if(c&&c.paid>c.drawn){const budgetReduction=Math.max(0,config.creditBudget-(config.installmentActive?config.installment:0));const reduction=card.id==='nbk'?Math.min(budgetReduction,nbkOpening):Math.max(0,budgetReduction-nbkOpening);const draw=Math.max(0,c.paid-c.drawn-reduction);if(draw>0){const ready=new Date(`${c.last}T12:00:00`);ready.setDate(ready.getDate()+config.wait);if(today<ready)return step('انتظر إتاحة إعادة السحب',`${card.name} • متوقع ${ready.toLocaleDateString('ar-EG')}، ثم أكد الاستلام الفعلي.`,'wait',draw,{card:card.id});return step(`استلمت السحب من ${card.name}؟`,'سجّل كل عملية بحد أقصى 10,000 جنيه وصافي المقبوض.','withdraw',Math.min(10000,draw),{card:card.id});}}}
 if(config.installmentActive||(m.installmentCarry||0)>0){const done=m.transactions.filter(t=>t.type==='installment').reduce((a,t)=>a+t.amount,0);const due=(config.installmentActive?config.installment:0)+(m.installmentCarry||0);if(done<due)return safe('سدّد قسط NBK A',due-done,'installment',{budget:'credit'});}
 const balance=c=>s.debt[c.id]-(s.cycles[c.id]?.drawn||0);
 const pending=config.cards.filter(c=>balance(c)>0);
 if(pending.length){const card=[...pending].sort((a,b)=>a.due-b.due||balance(a)-balance(b))[0];const end=new Date(today);end.setDate(end.getDate()+config.wait);const held=m.budgets.filter(b=>!['food','credit','rent','charity'].includes(b.id)).reduce((a,b)=>{const due=new Date(`${m.id}-${String(Math.min(b.due,new Date(Number(m.id.slice(0,4)),Number(m.id.slice(5)),0).getDate())).padStart(2,'0')}T12:00:00`);return due<=end?a+Math.max(0,b.amount-(s.paid[b.id]||0)):a;},0);return safe(`سدّد ${card.name}`,round(balance(card)+held),'repay',{card:card.id,principal:balance(card),held});}
 return step('كمّل التزامات الشهر','ابدأ بالأقرب موعدًا. سجّل الأكل عند الصرف، وباقي الصدقة وباقي البنود من الميزانية.','budget');
}
export function validate(data){
 const num=n=>typeof n==='number'&&Number.isFinite(n)&&n>=0&&n<=1e9;
 if(!data||data.version!==1||!data.settings||!Array.isArray(data.months)||!data.months.length)throw Error('ملف النسخة غير صالح');
 const s=data.settings;if(!num(s.rate)||!num(s.wait)||!Number.isInteger(s.wait)||s.wait>30||!num(s.fee)||s.fee>100||!num(s.installment)||!num(s.creditBudget)||typeof s.installmentActive!=='boolean'||!Array.isArray(s.cards)||s.cards.length!==2)throw Error('إعدادات غير صالحة');
 if(s.cards.some((c,i)=>c.id!==['nbk','nbe'][i]||typeof c.name!=='string'||!num(c.debt)||!Number.isInteger(c.due)||c.due<1||c.due>31))throw Error('بطاقات غير صالحة');
 const ids=new Set();for(const m of data.months){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(m.id)||ids.has(m.id)||!num(m.opening)||(m.installmentCarry!==undefined&&!num(m.installmentCarry))||typeof m.reviewed!=='boolean'||typeof m.foodReserved!=='boolean'||!Array.isArray(m.budgets)||!Array.isArray(m.transactions))throw Error('شهر غير صالح');if(data.months.indexOf(m)>0&&data.months[data.months.indexOf(m)-1].id>=m.id)throw Error('ترتيب الشهور غير صالح');ids.add(m.id);if(m.budgets.length!==defaults.length||defaults.some(([id])=>m.budgets.filter(b=>b.id===id).length!==1)||m.budgets.some(b=>typeof b.name!=='string'||!num(b.amount)||(b.baseAmount!==undefined&&!num(b.baseAmount))||!Number.isInteger(b.due)||b.due<1||b.due>31))throw Error('ميزانية غير صالحة');const tids=new Set();for(const t of m.transactions){if(typeof t.id!=='string'||tids.has(t.id)||!['income','expense','installment','repay','withdraw'].includes(t.type)||!num(t.amount)||!/^\d{4}-\d{2}-\d{2}$/.test(t.date)||Number.isNaN(Date.parse(t.date))||typeof t.note!=='string')throw Error('حركة غير صالحة');tids.add(t.id);if(['repay','withdraw'].includes(t.type)&&!s.cards.some(c=>c.id===t.card))throw Error('بطاقة غير صالحة');if(t.type==='repay'&&!num(t.fee))throw Error('رسوم غير صالحة');if(t.type==='withdraw'&&(!num(t.net)||t.net>t.amount||t.amount>10000))throw Error('سحب غير صالح');if(['expense','installment'].includes(t.type)&&!m.budgets.some(b=>b.id===t.budget))throw Error('بند غير صالح');}}
 return data;
}

export function nextMonth(state){const last=state.months.at(-1),d=new Date(last.id+'-02');d.setMonth(d.getMonth()+1);const s=stats(state,last),m=fresh().months[0];m.id=monthKey(d);m.opening=s.cash;const installmentPaid=last.transactions.filter(t=>t.type==='installment').reduce((a,t)=>a+t.amount,0);m.installmentCarry=Math.max(0,(state.settings.installmentActive?state.settings.installment:0)+(last.installmentCarry||0)-installmentPaid);m.budgets=last.budgets.map(b=>({...b,baseAmount:b.baseAmount??b.amount,amount:(b.baseAmount??b.amount)+(b.id==='credit'?0:Math.max(0,b.amount-(s.paid[b.id]||0)))}));m.budgets.find(b=>b.id==='credit').amount=state.settings.creditBudget+m.installmentCarry;return m;}
