import {test} from 'node:test';import assert from 'node:assert/strict';import {fresh,stats,guide,split,validate,nextMonth} from './core.js';
const tx=(type,amount,extra={})=>({id:crypto.randomUUID(),type,amount,date:'2026-10-01',note:'',...extra});
function setup(){const s=fresh(),m=s.months[0];m.id='2026-10';m.reviewed=true;return [s,m];}
test('defaults total 39100 and anticipated salary does not create cash',()=>{const [s,m]=setup();assert.equal(m.budgets.reduce((a,b)=>a+b.amount,0),39100);assert.equal(stats(s,m).cash,0);assert.equal(guide(s,m).action,'income');});
test('food reservation is not spending; partial expenses release only corresponding reserve',()=>{const [s,m]=setup();m.transactions.push(tx('income',33750,{source:'full'}));m.foodReserved=true;assert.equal(stats(s,m).cash,33750);assert.equal(stats(s,m).available,27250);m.transactions.push(tx('expense',500,{budget:'food'}));assert.equal(stats(s,m).cash,33250);assert.equal(stats(s,m).reserved,6000);assert.equal(stats(s,m).available,27250);});
test('card cash, debt and fees accounted separately',()=>{const [s,m]=setup();m.transactions.push(tx('income',50000,{source:'full'}),tx('repay',20000,{card:'nbk',fee:5}),tx('withdraw',10000,{card:'nbk',net:9900}),tx('withdraw',9500,{card:'nbk',net:9405}));const v=stats(s,m);assert.equal(v.cash,49300);assert.equal(v.debt.nbk,19500);assert.equal(v.fees,200);assert.equal(v.paid.credit,500);});
test('split Fawry limits and fee totals',()=>{assert.deepEqual(split(19500),[10000,9500]);assert.deepEqual(split(10194),[10000,194]);assert.equal(19500*.99,19305);});
test('wait then receive a partial withdrawal',()=>{const [s,m]=setup();m.foodReserved=true;m.transactions.push(tx('income',50000,{source:'full'}),tx('expense',4300,{budget:'rent'}),tx('expense',3000,{budget:'charity'}),tx('repay',10194,{card:'nbe',fee:0}));assert.equal(guide(s,m,new Date('2026-10-02T12:00:00')).action,'wait');assert.equal(guide(s,m,new Date('2026-10-03T13:00:00')).amount,10000);m.transactions.push(tx('withdraw',10000,{card:'nbe',net:9900}));assert.equal(guide(s,m,new Date('2026-10-03T13:00:00')).amount,194);});
test('insufficient cash cannot count future part-time income',()=>{const [s,m]=setup();m.foodReserved=true;m.transactions.push(tx('income',13800,{source:'full'}),tx('expense',4300,{budget:'rent'}),tx('expense',3000,{budget:'charity'}));assert.equal(guide(s,m).action,'blocked');assert.equal(stats(s,m).available,0);});
test('rate changes do not rewrite received income',()=>{const [s,m]=setup();m.transactions.push(tx('income',33000,{source:'full'}));s.settings.rate=60;assert.equal(stats(s,m).cash,33000);});
test('partial repayment remains pending after permitted redraw',()=>{const [s,m]=setup();m.foodReserved=true;m.transactions.push(tx('income',60000,{source:'full'}),tx('expense',4300,{budget:'rent'}),tx('expense',3000,{budget:'charity'}),tx('installment',1500,{budget:'credit'}),tx('repay',10194,{card:'nbe',fee:0}),tx('withdraw',10000,{card:'nbe',net:9900}),tx('withdraw',194,{card:'nbe',net:192.06}),tx('repay',5000,{card:'nbk',fee:0}),tx('withdraw',4500,{card:'nbk',net:4455}));const g=guide(s,m,new Date('2026-10-06'));assert.equal(g.action,'repay');assert.equal(g.principal,15000);});
test('backup round trip and corrupt files rejected',()=>{const [s,m]=setup();m.transactions.push(tx('income',30000,{source:'full'}));assert.deepEqual(validate(JSON.parse(JSON.stringify(s))),s);assert.throws(()=>validate({version:1}));const corrupt=structuredClone(s);corrupt.months[0].transactions.push(tx('withdraw',20000,{card:'nbk',net:19800}));assert.throws(()=>validate(corrupt));});
test('historical debt ignores future months',()=>{const [s,m]=setup();const later=structuredClone(m);later.id='2026-11';later.transactions=[tx('repay',500,{card:'nbk',fee:0,date:'2026-11-01'})];s.months.push(later);assert.equal(stats(s,m).debt.nbk,20000);assert.equal(stats(s,later).debt.nbk,19500);});
test('rollover carries actual cash and arrears without multiplying base budget',()=>{const [s,m]=setup();m.transactions.push(tx('income',10000,{source:'full'}),tx('expense',1000,{budget:'food'}),tx('installment',500,{budget:'credit'}));const next=nextMonth(s);assert.equal(next.opening,8500);assert.equal(next.installmentCarry,1000);assert.equal(next.budgets.find(b=>b.id==='credit').amount,3000);assert.equal(next.budgets.find(b=>b.id==='food').amount,12000);s.months.push(next);assert.equal(nextMonth(s).budgets.find(b=>b.id==='food').amount,18500);});
